"""
VetOnco — Feasibility Gate (ported from CrisPRO)
Computes free-drug Cmax vs IC50 gap ratio and returns a 3-band verdict.

BANDS (from CrisPRO source):
    PASS       : gap_ratio < 5×   (free Cmax exceeds IC50 by <5×)
    CONDITIONAL: 5× ≤ gap < 50×
    FAIL       : gap ≥ 50×

gap_ratio = IC50 / free_Cmax
free_Cmax = Cmax × (1 − PPB)

RATIONALE STRINGS: All arithmetic is hard-coded. No LLM text generation.
    The rationale string is a deterministic template — no natural language.

QUARANTINE POLICY:
    If pk_status != "VERIFIED", the gate returns UNVERIFIED immediately.
    No gap ratio is computed for unverified drugs.
"""
from __future__ import annotations
from typing import Optional


def compute_feasibility(drug_dict: dict) -> dict:
    """
    Compute feasibility gate for a drug.

    Parameters
    ----------
    drug_dict : dict with keys:
        pk_status           : "VERIFIED" | "UNVERIFIED"
        quarantine_reason   : str | None
        feasibility_gate    : dict with:
            ic50_um         : float | None
            cmax_um         : float | None
            plasma_protein_binding : float | None  (fraction 0.0–1.0)

    Returns
    -------
    dict with keys:
        verdict     : "PASS" | "CONDITIONAL" | "FAIL" | "UNVERIFIED"
        gap_ratio   : float | None
        free_cmax   : float | None
        rationale   : str  (hard-coded arithmetic, no LLM)
    """
    pk_status = drug_dict.get("pk_status", "UNVERIFIED")
    quarantine_reason = drug_dict.get("quarantine_reason")

    if pk_status != "VERIFIED":
        return {
            "verdict": "UNVERIFIED",
            "gap_ratio": None,
            "free_cmax": None,
            "rationale": f"UNVERIFIED: {quarantine_reason or 'No primary canine PK study'}",
        }

    gate = drug_dict.get("feasibility_gate", {})
    ic50 = gate.get("ic50_um")
    cmax = gate.get("cmax_um")
    ppb  = gate.get("plasma_protein_binding")

    if ic50 is None or cmax is None or ppb is None:
        return {
            "verdict": "UNVERIFIED",
            "gap_ratio": None,
            "free_cmax": None,
            "rationale": "UNVERIFIED: One or more PK values missing (ic50, cmax, ppb)",
        }

    free_cmax = round(cmax * (1.0 - ppb), 6)

    if free_cmax <= 0:
        return {
            "verdict": "FAIL",
            "gap_ratio": None,
            "free_cmax": free_cmax,
            "rationale": f"FAIL: free_cmax={free_cmax:.6f}µM ≤ 0 (PPB={ppb:.0%} leaves no free drug)",
        }

    gap_ratio = round(ic50 / free_cmax, 4)

    if gap_ratio < 5.0:
        verdict = "PASS"
    elif gap_ratio < 50.0:
        verdict = "CONDITIONAL"
    else:
        verdict = "FAIL"

    # Hard-coded rationale — deterministic template, no LLM
    # All numbers computed from inputs, not generated by language model
    rationale = _build_rationale(ic50, cmax, ppb, free_cmax, gap_ratio, verdict)

    return {
        "verdict": verdict,
        "gap_ratio": gap_ratio,
        "free_cmax": free_cmax,
        "rationale": rationale,
    }


def _build_rationale(
    ic50: float,
    cmax: float,
    ppb: float,
    free_cmax: float,
    gap_ratio: float,
    verdict: str,
) -> str:
    """
    Build a deterministic rationale string from arithmetic inputs.
    NO LLM. NO natural language generation. Template only.

    Example output:
        "PASS | ic50=0.0100µM | cmax=0.2200µM | ppb=93% |
         free_cmax=0.0154µM | gap=0.65× | free_cmax/ic50=1.54×"
    """
    coverage = round(free_cmax / ic50, 4) if ic50 > 0 else 0.0
    return (
        f"{verdict} | "
        f"ic50={ic50:.4f}µM | "
        f"cmax={cmax:.4f}µM | "
        f"ppb={ppb:.0%} | "
        f"free_cmax={free_cmax:.4f}µM | "
        f"gap={gap_ratio:.2f}× | "
        f"free_cmax/ic50={coverage:.2f}×"
    )
